eureka:
  instance:
    prefer-ip-address = true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultzone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enables: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      LIBRARY:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED

      MEMBER:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6S
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
